services:
  - type: web
    name: scrapper-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        value: hidev
      - key: NEWS_API_KEY
        value: 6829434b7662434e992ed2d0613b8d9d
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: false
