services:
  - type: web
    name: media-insights-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: true
