services:
  - type: web
    name: media-insights-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: true
